run init job only if required

diff --git a/charts/epi/templates/job-init.yaml b/charts/epi/templates/job-init.yaml
--- a/charts/epi/templates/job-init.yaml
+++ b/charts/epi/templates/job-init.yaml
@@ -1,4 +1,10 @@
 {{- /*
+Please note: The Init Job only runs if the image differs from last build
+*/}}
+
+{{- if ne (include "epi.lastBuiltImage" .) (include "epi.image" .) -}}
+
+{{- /*
 1. Create Configmaps required for hook from template
 */}}
 
@@ -28,7 +34,6 @@ rules:
   - ""
   resourceNames:
   - {{ include "epi.configMapSeedsBackupName" . | quote }}
-  - "{{ include "epi.fullname" . }}-build-info"
   resources:
   - configmaps
   verbs:
@@ -113,39 +118,6 @@ spec:
       {{- end }}
       restartPolicy: Never
       initContainers:
-      - name: build-necessity-check
-        {{- if .Values.kubectl.image.sha }}
-        image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}@sha256:{{ .Values.kubectl.image.sha }}"
-        {{- else }}
-        image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
-        {{- end }}
-        imagePullPolicy: {{ .Values.kubectl.image.pullPolicy | default "IfNotPresent" }}
-        command:
-          - sh
-          - -c
-        args:
-          - |
-            # Exit on error
-            set -e
-            last_built_image=$(kubectl get cm --ignore-not-found {{ include "epi.fullname" . }}-build-info -o jsonpath='{.data.lastBuiltImage}')
-            if [ "$last_built_image" != "$FULL_IMAGE" ]
-            then 
-              echo "=======> Not build yet for image=$FULL_IMAGE!"
-              echo "=======> Writing signal file in order to start build process ..."
-              touch /container-shared-data/doBuild
-            else
-              echo "=======> Already built for image=$FULL_IMAGE"
-            fi
-            echo "=======> Exiting ..."
-            exit 0
-        env:
-          - name: FULL_IMAGE
-            value: {{ include "epi.image" . | quote }}
-        volumeMounts:
-            # We mount a temporary volume in order to signal if build process must run or not
-          - name: container-shared-data
-            mountPath: /container-shared-data
-            readOnly: false
       - name: init-epi
         image: {{ include "epi.image" . | quote }}
         imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
@@ -164,35 +136,29 @@ spec:
           - |
             # Exit on error
             set -e
-            # 1. Check if build process needs to be done by checking if build process has not been executed in the past for current Image Tag.
-            # 2. If yes: Start server in background, wait, run build and copy seedBackup to shared folder with main container.
+            # Start server in background, wait, run build and copy seedBackup to shared folder with main container.
             cd /ePI-workspace
-            if [ -f /container-shared-data/doBuild ]
-            then 
-              echo "=======> Not build yet!"
-              echo "=======> Copying seedsBackupOnStartup to seedsBackup ..."
-              cp apihub-root/seedsBackupOnStartup apihub-root/seedsBackup
-              echo "=======> Starting application in background process ..."
-              npm run server &
-              server_pid=$!
-              echo "=======> Application running in background with PID=$server_pid"
-              echo "=======> Sleeping for {{ .Values.config.sleepTime }} ..."
-              sleep {{ .Values.config.sleepTime }}
-              echo "=======> Starting build process ..."
-              npm run build-all
-              rc=$?
-              echo "=======> Build process done - rc=$rc"
-              if [ $rc -eq 0 ]
-              then 
-                echo "=======> Copying seedsBackup to container-shared-data ..."
-                cp /ePI-workspace/apihub-root/seedsBackup /container-shared-data
-                ls -las /container-shared-data
-              else
-                echo "=======> ERROR during build process - Exiting with rc=$rc ..."
-                exit $rc
-              fi
+            echo "=======> Not build yet!"
+            echo "=======> Copying seedsBackupOnStartup to seedsBackup ..."
+            cp apihub-root/seedsBackupOnStartup apihub-root/seedsBackup
+            echo "=======> Starting application in background process ..."
+            npm run server &
+            server_pid=$!
+            echo "=======> Application running in background with PID=$server_pid"
+            echo "=======> Sleeping for {{ .Values.config.sleepTime }} ..."
+            sleep {{ .Values.config.sleepTime }}
+            echo "=======> Starting build process ..."
+            npm run build-all
+            rc=$?
+            echo "=======> Build process done - rc=$rc"
+            if [ $rc -eq 0 ]
+            then
+              echo "=======> Copying seedsBackup to container-shared-data ..."
+              cp /ePI-workspace/apihub-root/seedsBackup /container-shared-data
+              ls -las /container-shared-data
             else
-              echo "=======> Already built for version=$IMAGE_TAG"
+              echo "=======> ERROR during build process - Exiting with rc=$rc ..."
+              exit $rc
             fi
             echo "=======> Exiting ..."
             exit 0
@@ -255,11 +221,7 @@ spec:
             readOnly: false
       containers:
       - name: write-configmap
-        {{- if .Values.kubectl.image.sha }}
-        image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}@sha256:{{ .Values.kubectl.image.sha }}"
-        {{- else }}
-        image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
-        {{- end }}
+        image: {{ include "epi.kubectlImage" . | quote }}
         imagePullPolicy: {{ .Values.kubectl.image.pullPolicy | default "IfNotPresent" }}
         command:
           - sh
@@ -322,3 +284,5 @@ spec:
       tolerations:
         {{- toYaml . | nindent 8 }}
       {{- end }}
+
+{{- end -}}
